In [1]:
import pygor3 as p3
%cd /home/alfaceor/Dropbox/PosDoc/IGoR/dev/MyGithub/pygor3/demo/thi/synthetic_data
db = p3.IgorSqliteDB.create_db("Ajam.db")
mdl = db.get_IgorModel()
seq_index=3

/home/alfaceor/Dropbox/PosDoc/IGoR/dev/MyGithub/pygor3/demo/thi/synthetic_data
ErrorRate_record :  ('SingleErrorRate', '0.000396072')
----- Marginals -----
d_3_del
d_5_del
d_gene
dj_dinucl
dj_ins
j_5_del
j_choice
v_3_del
v_choice
vd_dinucl
vd_ins


In [2]:
bs_df = db.get_IgorBestScenariosDataframe_By_seq_index(seq_index)
bs_list = db.get_IgorBestScenarios_By_seq_index_IgorModel(seq_index, mdl)

In [3]:
bs = bs_list[0]
bs_real = mdl.parms.realiz_dict_from_scenario(bs)

vd_dinucl [0, 0, 2] DinucMarkov
dj_dinucl [0] DinucMarkov
v_choice 60 GeneChoice
d_gene 1 GeneChoice
j_choice 8 GeneChoice
v_3_del 2 Deletion
d_3_del 12 Deletion
d_5_del 4 Deletion
j_5_del 6 Deletion
vd_ins 3 Insertion
dj_ins 1 Insertion


In [9]:
len(bs_real['v_choice'].value)

287

In [51]:
bs_df[bs_df['id_v_choice']==59] #['scenario_proba_cond_seq']

seq_index  scenario_rank  scenario_proba_cond_seq  id_v_choice  \
1          3              2                 0.106228           59   
4          3              5                 0.051306           59   
5          3              6                 0.049664           59   
9          3             10                 0.025105           59   

   id_j_choice  id_d_gene  id_v_3_del  id_d_5_del  id_d_3_del  id_j_5_del  \
1            8          1           2           4          12           6   
4            8          1           2           5          12           6   
5            8          1           2           4          12           7   
9            8          1           2           4          12           8   

   id_vd_ins  vd_dinucl  id_dj_ins dj_dinucl mismatches  mismatcheslen  
1          3    [0,0,2]          1       [0]      [261]              1  
4          4  [0,0,2,2]          1       [0]      [261]              1  
5          3    [0,0,2]          2     [0,0]      [261]              1  
9          3    [0,0,2]          3   [0,0,0]      [261]              1

In [52]:
bs_df[bs_df['id_v_choice']==60] #['scenario_proba_cond_seq']

seq_index  scenario_rank  scenario_proba_cond_seq  id_v_choice  \
0          3              1                 0.112082           60   
2          3              3                 0.054133           60   
3          3              4                 0.052401           60   
6          3              7                 0.026489           60   
7          3              8                 0.025330           60   
8          3              9                 0.025309           60   

   id_j_choice  id_d_gene  id_v_3_del  id_d_5_del  id_d_3_del  id_j_5_del  \
0            8          1           2           4          12           6   
2            8          1           2           5          12           6   
3            8          1           2           4          12           7   
6            8          1           2           4          12           8   
7            8          1           2           6          12           6   
8            8          1           2           5          12           7   

   id_vd_ins    vd_dinucl  id_dj_ins dj_dinucl mismatches  mismatcheslen  
0          3      [0,0,2]          1       [0]      [261]              1  
2          4    [0,0,2,2]          1       [0]      [261]              1  
3          3      [0,0,2]          2     [0,0]      [261]              1  
6          3      [0,0,2]          3   [0,0,0]      [261]              1  
7          5  [0,0,2,2,2]          1       [0]      [261]              1  
8          4    [0,0,2,2]          2     [0,0]      [261]              1

In [67]:
event_nickname1='v_choice'
event_nickname2='j_choice'
da = mdl.get_zero_xarray_from_list([event_nickname1, event_nickname2])
da.sum()

<xarray.DataArray ()>
array(0.)

In [71]:
import xarray as xr
def scenario_function(bs:p3.IgorScenario):
    ev_dict_ids = {event_nickname1: bs[event_nickname1], event_nickname2: bs[event_nickname2]}
    darr = xr.zeros_like(da)
    darr[ev_dict_ids] = 1
    return darr
#     import xarray as xr
#     return xr.zeros_like(da)[ev_dict_ids] = 1
#     return mdl.get_zero_xarray_from_list([event_nickname1, event_nickname2])[ev_dict_ids] = 1
    

In [72]:
bs_list = db.get_IgorBestScenarios_By_seq_index_IgorModel(seq_index, mdl)
bs = bs_list[0]
print(bs.to_dict())

{'seq_index': 3, 'scenario_rank': 1, 'scenario_proba_cond_seq': 0.112082, 'vd_dinucl': [0, 0, 2], 'dj_dinucl': [0], 'mismatches': [261], 'mismatcheslen': 1, 'v_choice': 60, 'd_gene': 1, 'j_choice': 8, 'v_3_del': 2, 'd_3_del': 12, 'd_5_del': 4, 'j_5_del': 6, 'vd_ins': 3, 'dj_ins': 1}


In [73]:
bs_counts = 0
for bs in bs_list:
    bs_counts = bs_counts + scenario_function(bs)
bs_counts[{'v_choice':59}]


<xarray.DataArray (j_choice: 15)>
array([0., 0., 0., 0., 0., 0., 0., 0., 4., 0., 0., 0., 0., 0., 0.])
Coordinates:
    v_choice       int64 59
    lbl__v_choice  object 'X61445|TRBV6-2*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |'
  * j_choice       (j_choice) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
    lbl__j_choice  (j_choice) object 'K02545|TRBJ1-1*01|Homo sapiens|F|J-REGION|749..796|48 nt|3| | | | |48+0=48| | |' ... 'X02987|TRBJ2-7*02|Homo sapiens|ORF|J-REGION|1890..1936|47 nt|2| | | | |47+0=47| | |'

In [36]:
import numpy as np
np.where(bs_counts == 0)

(array([ 0,  0,  0, ..., 88, 88, 88]), array([ 0,  1,  2, ..., 12, 13, 14]))

In [74]:
bs_counts[{'v_choice':59, 'j_choice':0}] =1
bs_counts[{'v_choice':59}]+bs_counts[{'v_choice':59}]

<xarray.DataArray (j_choice: 15)>
array([2., 0., 0., 0., 0., 0., 0., 0., 8., 0., 0., 0., 0., 0., 0.])
Coordinates:
    v_choice       int64 59
    lbl__v_choice  object 'X61445|TRBV6-2*01|Homo sapiens|F|V-REGION|412..698|287 nt|1| | | | |287+0=287| | |'
  * j_choice       (j_choice) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
    lbl__j_choice  (j_choice) object 'K02545|TRBJ1-1*01|Homo sapiens|F|J-REGION|749..796|48 nt|3| | | | |48+0=48| | |' ... 'X02987|TRBJ2-7*02|Homo sapiens|ORF|J-REGION|1890..1936|47 nt|2| | | | |47+0=47| | |'

In [54]:
bs_counts[{'v_choice':60}]


<xarray.DataArray (j_choice: 15)>
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,
        0.])
Coordinates:
    v_choice       int64 60
    lbl__v_choice  object 'U07978|TRBV6-3*01|Homo sapiens|F|V-REGION|29129..29415|287 nt|1| | | | |287+0=287| | |'
  * j_choice       (j_choice) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
    lbl__j_choice  (j_choice) object 'K02545|TRBJ1-1*01|Homo sapiens|F|J-REGION|749..796|48 nt|3| | | | |48+0=48| | |' ... 'X02987|TRBJ2-7*02|Homo sapiens|ORF|J-REGION|1890..1936|47 nt|2| | | | |47+0=47| | |'

In [59]:
da[{'v_choice':60}]

<xarray.DataArray (j_choice: 15)>
array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])
Coordinates:
    v_choice       int64 60
    lbl__v_choice  object 'U07978|TRBV6-3*01|Homo sapiens|F|V-REGION|29129..29415|287 nt|1| | | | |287+0=287| | |'
  * j_choice       (j_choice) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
    lbl__j_choice  (j_choice) object 'K02545|TRBJ1-1*01|Homo sapiens|F|J-REGION|749..796|48 nt|3| | | | |48+0=48| | |' ... 'X02987|TRBJ2-7*02|Homo sapiens|ORF|J-REGION|1890..1936|47 nt|2| | | | |47+0=47| | |'

In [76]:
import matplotlib.pyplot as plt
axd = plt.figure(constrained_layout=True).subplot_mosaic(
    """
    .a.
    bAc
    .d.
    """,
    gridspec_kw={
        # set the height ratios between the rows
        "height_ratios": [1, 3.5, 1],
        # set the width ratios between the columns
        "width_ratios": [1, 3.5, 1],
    },
)
identify_axes(axd)


AttributeError: 'Figure' object has no attribute 'subplot_mosaic'

<Figure size 432x288 with 0 Axes>

In [77]:
import matplotlib
matplotlib.__version__

'3.0.3'